<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartStay.Application\SmartStay.Application.csproj" />
    <ProjectReference Include="..\SmartStay.Contract\SmartStay.Contract.csproj" />
    <ProjectReference Include="..\SmartStay.Domain\SmartStay.Domain.csproj" />
    <ProjectReference Include="..\SmartStay.Infrastructure\SmartStay.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartStay.Persistence\SmartStay.Persistence.csproj" />
    <ProjectReference Include="..\SmartStay.Presentation\SmartStay.Presentation.csproj" />
  </ItemGroup>

</Project>
